/**
 * Real tests for the binary AndroidManifest (AXML) parser.
 *
 * The sample manifest is checked in as a fixture because it must be the real
 * AAPT2-compiled output from an APK, not something generated by the test. The
 * expected values below were read from `aapt2 dump badging` on that same APK.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { parseBinaryManifest, ANDROID_NS } from '../src/lib/axml.ts';

const fixture = path.join(import.meta.dirname, 'fixtures', 'AndroidManifest.bin.xml');
const manifest = fs.readFileSync(fixture);

test('rejects a buffer that is not a binary manifest', () => {
  assert.equal(parseBinaryManifest(Buffer.from('<manifest/>')), null);
  assert.equal(parseBinaryManifest(Buffer.alloc(0)), null);
  assert.equal(parseBinaryManifest(Buffer.from([0xff, 0xff, 0x01, 0x00, 0, 0, 0, 0])), null);
});

test('decodes the package name from the real compiled manifest', () => {
  const parsed = parseBinaryManifest(manifest);
  assert.ok(parsed, 'expected a parsed manifest');
  assert.equal(parsed.packageName, 'com.myaistudio.calculator');
});

test('decodes version and SDK attributes', () => {
  const parsed = parseBinaryManifest(manifest)!;
  assert.equal(parsed.versionCode, 1);
  assert.equal(parsed.minSdk, 24);
  assert.equal(parsed.targetSdk, 34);
});

test('classifies components by their real element type', () => {
  const parsed = parseBinaryManifest(manifest)!;
  assert.ok(
    parsed.activities.some((a) => a.endsWith('MainActivity')),
    `expected MainActivity in ${JSON.stringify(parsed.activities)}`,
  );
  assert.ok(parsed.mainActivity?.endsWith('MainActivity'), 'expected a launcher activity');
  // The library-injected receiver belongs under receivers. The previous
  // string-pool approach classified every dotted string as an activity, so this
  // assertion is what distinguishes a real parse from a guess.
  assert.deepEqual(parsed.receivers, ['androidx.profileinstaller.ProfileInstallReceiver']);
  assert.deepEqual(parsed.providers, ['androidx.startup.InitializationProvider']);
  assert.equal(parsed.services.length, 0);
  assert.equal(parsed.activities.length, 1);
});

test('reports debuggable from the real manifest attribute', () => {
  const parsed = parseBinaryManifest(manifest)!;
  assert.equal(parsed.debuggable, true);
});

test('reads framework attribute names from the resource map', () => {
  // AAPT2 leaves these pool entries empty, so a naive reader cannot see them.
  const parsed = parseBinaryManifest(manifest)!;
  assert.equal(parsed.versionName, '1.0');
  assert.equal(ANDROID_NS, 'http://schemas.android.com/apk/res/android');
});
