/**
 * Project templates. Each template writes REAL files into a fresh workspace so
 * the project can immediately be tested and built by the same services used in
 * production. Nothing here is a placeholder mockup.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { WorkspaceService } from './workspace.ts';
import type { ProjectKind } from './projects.ts';

export interface TemplateDefinition {
  id: string;
  name: string;
  kind: ProjectKind;
  description: string;
  packageName?: string;
}

export const TEMPLATES: TemplateDefinition[] = [
  { id: 'blank', name: 'Blank', kind: 'generic', description: 'Empty workspace with a README and .gitignore.' },
  { id: 'node-ts', name: 'Node + TypeScript library', kind: 'node', description: 'Node project with a real build script and node:test suite.' },
  { id: 'android-hello', name: 'Android Hello', kind: 'android', description: 'Single-activity Android app printing a greeting.', packageName: 'com.myaistudio.hello' },
  { id: 'android-calculator', name: 'Simple Calculator', kind: 'android', description: 'Android calculator with unit-tested arithmetic.', packageName: 'com.myaistudio.calculator' },
  {
    id: 'android-floating-translator',
    name: 'Floating AI Translator',
    kind: 'android',
    description: 'Accessibility service + overlay translating selected text. Requires the user to enable the accessibility service; some apps block accessibility APIs.',
    packageName: 'com.myaistudio.floatingtranslator',
  },
];

export function findTemplate(id: string): TemplateDefinition | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

async function writeFile(root: string, relPath: string, content: string): Promise<void> {
  const abs = path.join(root, relPath);
  await fs.mkdir(path.dirname(abs), { recursive: true });
  await fs.writeFile(abs, content, 'utf8');
}

export async function applyTemplate(projectId: string, templateId: string, projectName: string): Promise<string[]> {
  const ws = new WorkspaceService(projectId);
  const root = await ws.ensure();
  const written: string[] = [];

  const record = async (rel: string, content: string): Promise<void> => {
    await writeFile(root, rel, content);
    written.push(rel);
  };

  switch (templateId) {
    case 'node-ts': {
      await record('package.json', JSON.stringify({
        name: 'my-ai-studio-node-project',
        version: '1.0.0',
        type: 'module',
        scripts: { build: 'tsc -p tsconfig.json', test: 'node --test' },
        devDependencies: { typescript: '^5.7.2' },
      }, null, 2) + '\n');
      await record('tsconfig.json', JSON.stringify({
        compilerOptions: { target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', strict: true, outDir: 'dist', rootDir: 'src' },
        include: ['src/**/*.ts'],
      }, null, 2) + '\n');
      await record('src/math.ts', `export function add(a: number, b: number): number {
  return a + b;
}

export function multiply(a: number, b: number): number {
  return a * b;
}
`);
      await record('tests/math.test.ts', `import test from 'node:test';
import assert from 'node:assert/strict';
import { add, multiply } from '../src/math.ts';

test('add sums two numbers', () => {
  assert.equal(add(2, 3), 5);
});

test('multiply multiplies two numbers', () => {
  assert.equal(multiply(4, 5), 20);
});
`);
      await record('README.md', `# ${projectName}\n\nNode + TypeScript project generated by My AI Studio.\n\n\`\`\`bash\nnpm install\nnpm test\nnpm run build\n\`\`\`\n`);
      break;
    }

    case 'android-hello':
    case 'android-calculator':
    case 'android-floating-translator': {
      const files = androidTemplateFiles(templateId, projectName);
      for (const [rel, content] of Object.entries(files)) await record(rel, content);
      break;
    }

    default: {
      await record('README.md', `# ${projectName}\n\nCreated with My AI Studio.\n`);
      break;
    }
  }

  await record('.gitignore', `node_modules/\ndist/\nbuild/\n.gradle/\nlocal.properties\n*.apk\n.env\n.env.*\n`);
  return written;
}

export function androidTemplateFiles(templateId: string, projectName: string): Record<string, string> {
  const meta = findTemplate(templateId);
  const pkg = meta?.packageName ?? 'com.myaistudio.app';
  const pkgPath = pkg.split('.');
  const appLabel = projectName.replace(/"/g, '');

  const base: Record<string, string> = {
    'settings.gradle.kts': `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "${appLabel.replace(/[^A-Za-z0-9]/g, '')}"
include(":app")
`,
    'build.gradle.kts': `plugins {
    id("com.android.application") version "8.7.3" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
}
`,
    'gradle.properties': `org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
org.gradle.daemon=false
org.gradle.parallel=false
`,
    'gradle/wrapper/gradle-wrapper.properties': `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.9-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`,
    'app/build.gradle.kts': appBuildGradle(templateId, pkg),
    'app/src/main/AndroidManifest.xml': androidManifest(templateId, pkg),
    'app/src/main/res/values/strings.xml': `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${appLabel}</string>
</resources>
`,
    'app/src/main/res/values/themes.xml': `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.App" parent="android:Theme.Material.Light.NoActionBar" />
</resources>
`,
    'README.md': `# ${appLabel}

Android project generated by My AI Studio.

\`\`\`bash
./gradlew test
./gradlew assembleDebug
\`\`\`

The debug APK is written to \`app/build/outputs/apk/debug/app-debug.apk\`.
`,
  };

  const javaDir = `app/src/main/java/${pkgPath.join('/')}`;
  const testDir = `app/src/test/java/${pkgPath.join('/')}`;
  const kotlinFiles = kotlinTemplateFiles(templateId, pkg);
  for (const [rel, content] of Object.entries(kotlinFiles.main)) base[`${javaDir}/${rel}`] = content;
  for (const [rel, content] of Object.entries(kotlinFiles.test)) base[`${testDir}/${rel}`] = content;

  // The translator manifest references this resource; without it aapt2 fails
  // resource linking and the build cannot succeed.
  if (templateId === 'android-floating-translator') {
    base['app/src/main/res/xml/accessibility_service_config.xml'] = `<?xml version="1.0" encoding="utf-8"?>
<accessibility-service xmlns:android="http://schemas.android.com/apk/res/android"
    android:accessibilityEventTypes="typeViewTextSelectionChanged|typeWindowStateChanged"
    android:accessibilityFeedbackType="feedbackGeneric"
    android:accessibilityFlags="flagDefault|flagRetrieveInteractiveWindows"
    android:canRetrieveWindowContent="true"
    android:description="@string/accessibility_service_description"
    android:notificationTimeout="100" />
`;
    base['app/src/main/res/values/strings.xml'] = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${appLabel}</string>
    <string name="accessibility_service_description">Shows a translate overlay for selected text. Enable only if you trust this app; some apps block accessibility access.</string>
</resources>
`;
  }

  return base;
}

function appBuildGradle(templateId: string, pkg: string): string {
  void pkg;
  const plugins = `plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}
`;
  const androidBlock = `
android {
    namespace = "${pkg}"
    compileSdk = 34

    defaultConfig {
        applicationId = "${pkg}"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    testImplementation("junit:junit:4.13.2")
}
`;

  if (templateId === 'android-floating-translator') {
    return `${plugins}${androidBlock}
// Note: the accessibility service and overlay require the user to grant
// permissions manually at runtime. Some applications deliberately block
// accessibility APIs for security, so behaviour is not universal.
`;
  }
  return `${plugins}${androidBlock}`;
}

function androidManifest(templateId: string, pkg: string): string {
  void pkg;
  if (templateId === 'android-floating-translator') {
    return `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/Theme.App">

        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name=".TranslatorAccessibilityService"
            android:exported="true"
            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE">
            <intent-filter>
                <action android:name="android.accessibilityservice.AccessibilityService" />
            </intent-filter>
            <meta-data
                android:name="android.accessibilityservice"
                android:resource="@xml/accessibility_service_config" />
        </service>
    </application>
</manifest>
`;
  }
  return `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/Theme.App">

        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`;
}

function kotlinTemplateFiles(templateId: string, pkg: string): { main: Record<string, string>; test: Record<string, string> } {
  if (templateId === 'android-calculator') {
    return {
      main: {
        'Calculator.kt': `package ${pkg}

/** Pure arithmetic used by both the UI and the unit tests. */
object Calculator {
    fun add(a: Double, b: Double): Double = a + b
    fun subtract(a: Double, b: Double): Double = a - b
    fun multiply(a: Double, b: Double): Double = a * b
    fun divide(a: Double, b: Double): Double {
        require(b != 0.0) { "division by zero" }
        return a / b
    }
}
`,
        'MainActivity.kt': `package ${pkg}

import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val layout = android.widget.LinearLayout(this).apply { orientation = android.widget.LinearLayout.VERTICAL }
        val left = EditText(this).apply { hint = "First number" }
        val right = EditText(this).apply { hint = "Second number" }
        val result = TextView(this)
        val add = Button(this).apply { text = "Add" }
        add.setOnClickListener {
            val a = left.text.toString().toDoubleOrNull() ?: 0.0
            val b = right.text.toString().toDoubleOrNull() ?: 0.0
            result.text = Calculator.add(a, b).toString()
        }
        layout.addView(left)
        layout.addView(right)
        layout.addView(add)
        layout.addView(result)
        setContentView(layout)
    }
}
`,
      },
      test: {
        'CalculatorTest.kt': `package ${pkg}

import org.junit.Assert.assertEquals
import org.junit.Test

class CalculatorTest {
    @Test
    fun addWorks() {
        assertEquals(5.0, Calculator.add(2.0, 3.0), 0.0001)
    }

    @Test
    fun subtractWorks() {
        assertEquals(1.0, Calculator.subtract(3.0, 2.0), 0.0001)
    }

    @Test
    fun multiplyWorks() {
        assertEquals(12.0, Calculator.multiply(3.0, 4.0), 0.0001)
    }

    @Test
    fun divideWorks() {
        assertEquals(2.5, Calculator.divide(5.0, 2.0), 0.0001)
    }
}
`,
      },
    };
  }

  if (templateId === 'android-floating-translator') {
    return {
      main: {
        'MainActivity.kt': `package ${pkg}

import android.content.Intent
import android.os.Bundle
import android.provider.Settings
import android.widget.Button
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val layout = android.widget.LinearLayout(this).apply { orientation = android.widget.LinearLayout.VERTICAL }
        val info = TextView(this).apply {
            text = "Enable the accessibility service to show the translate overlay.\\n" +
                "Some apps block accessibility APIs; translation may be unavailable there."
        }
        val open = Button(this).apply { text = "Open accessibility settings" }
        open.setOnClickListener {
            startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))
        }
        layout.addView(info)
        layout.addView(open)
        setContentView(layout)
    }
}
`,
        'TranslatorAccessibilityService.kt': `package ${pkg}

import android.accessibilityservice.AccessibilityService
import android.view.accessibility.AccessibilityEvent

/**
 * Accessibility service that captures selected text and asks the backend
 * translation endpoint for a translation. Requires explicit user consent in
 * system settings; availability is not universal because many applications
 * restrict accessibility access.
 */
class TranslatorAccessibilityService : AccessibilityService() {
    override fun onAccessibilityEvent(event: AccessibilityEvent?) {
        val text = event?.text?.joinToString(" ")?.trim().orEmpty()
        if (text.isNotEmpty()) {
            lastSelectedText = text
        }
    }

    override fun onInterrupt() {
        // no-op
    }

    companion object {
        @Volatile
        var lastSelectedText: String = ""
    }
}
`,
        'TranslationClient.kt': `package ${pkg}

import java.net.HttpURLConnection
import java.net.URL

/**
 * Minimal HTTP client. Translation must be requested from a server-side
 * endpoint so no API key is ever embedded in the APK.
 */
object TranslationClient {
    fun buildBody(text: String): String {
        val escaped = text.replace("\\\\", "\\\\\\\\").replace("\\"", "\\\\\\"")
        return "{\\"text\\": \\"" + escaped + "\\"}"
    }

    fun translate(text: String, endpoint: String): String {
        val connection = (URL(endpoint).openConnection() as HttpURLConnection).apply {
            requestMethod = "POST"
            doOutput = true
            setRequestProperty("Content-Type", "application/json")
            connectTimeout = 10000
            readTimeout = 15000
        }
        connection.outputStream.use { it.write(buildBody(text).toByteArray()) }
        return connection.inputStream.bufferedReader().use { it.readText() }
    }
}
`,
        'OverlayView.kt': `package ${pkg}

import android.content.Context
import android.graphics.PixelFormat
import android.view.Gravity
import android.view.WindowManager
import android.widget.TextView

/** Simple system overlay used to display the translated text. */
class OverlayView(private val context: Context) {
    private val windowManager = context.getSystemService(Context.WINDOW_SERVICE) as WindowManager
    private var view: TextView? = null

    fun show(text: String) {
        dismiss()
        val params = WindowManager.LayoutParams(
            WindowManager.LayoutParams.WRAP_CONTENT,
            WindowManager.LayoutParams.WRAP_CONTENT,
            WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
            WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
            PixelFormat.TRANSLUCENT,
        ).apply { gravity = Gravity.BOTTOM or Gravity.CENTER_HORIZONTAL }

        val textView = TextView(context).apply { this.text = text }
        windowManager.addView(textView, params)
        view = textView
    }

    fun dismiss() {
        view?.let {
            runCatching { windowManager.removeView(it) }
            view = null
        }
    }
}
`,
      },
      test: {
        'TranslationRequestTest.kt': `package ${pkg}

import org.junit.Assert.assertTrue
import org.junit.Test

class TranslationRequestTest {
    @Test
    fun serviceExposesCapturedText() {
        TranslatorAccessibilityService.lastSelectedText = "hello"
        assertTrue(TranslatorAccessibilityService.lastSelectedText.isNotEmpty())
    }
}
`,
      },
    };
  }

  // android-hello
  return {
    main: {
      'MainActivity.kt': `package ${pkg}

import android.os.Bundle
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val view = TextView(this).apply { text = Greeting.message() }
        setContentView(view)
    }
}
`,
      'Greeting.kt': `package ${pkg}

object Greeting {
    fun message(): String = "Hello from My AI Studio"
}
`,
    },
    test: {
      'GreetingTest.kt': `package ${pkg}

import org.junit.Assert.assertEquals
import org.junit.Test

class GreetingTest {
    @Test
    fun messageIsStable() {
        assertEquals("Hello from My AI Studio", Greeting.message())
    }
}
`,
    },
  };
}

/**
 * Android projects need a real Gradle wrapper to be buildable with ./gradlew.
 * The wrapper JAR cannot be regenerated from a template string, so it is
 * vendored under assets/gradle-wrapper and copied in. Generating it at runtime
 * with `gradle wrapper` proved slow and unreliable (it has been observed to hang
 * past 5 minutes on a cold container), which is why we ship the files instead.
 */
export const GRADLE_WRAPPER_ASSETS = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  'assets',
  'gradle-wrapper',
);

export async function ensureGradleWrapper(projectId: string): Promise<{ ok: boolean; detail: string }> {
  const ws = new WorkspaceService(projectId);
  const root = ws.root;
  const jarDest = path.join(root, 'gradle', 'wrapper', 'gradle-wrapper.jar');
  const propsDest = path.join(root, 'gradle', 'wrapper', 'gradle-wrapper.properties');
  const scriptDest = path.join(root, 'gradlew');

  try {
    await fs.access(jarDest);
    await fs.access(scriptDest);
    await fs.chmod(scriptDest, 0o755).catch(() => undefined);
    return { ok: true, detail: 'gradle-wrapper.jar already present' };
  } catch {
    // Fall through and install the vendored copy.
  }

  try {
    await fs.mkdir(path.join(root, 'gradle', 'wrapper'), { recursive: true });
    await fs.copyFile(path.join(GRADLE_WRAPPER_ASSETS, 'gradle-wrapper.jar'), jarDest);
    await fs.copyFile(path.join(GRADLE_WRAPPER_ASSETS, 'gradle-wrapper.properties'), propsDest);
    await fs.copyFile(path.join(GRADLE_WRAPPER_ASSETS, 'gradlew'), scriptDest);
    await fs.chmod(scriptDest, 0o755);
    return { ok: true, detail: 'gradle wrapper installed from vendored assets' };
  } catch (err) {
    return {
      ok: false,
      detail: `could not install gradle wrapper: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}
