import { Router } from 'express';
import type { Request } from 'express';
import { z } from 'zod';
import { asyncHandler, HttpError, validate } from '../middleware/validate.ts';
import { requireAuth } from '../middleware/auth.ts';
import { rateLimit } from '../middleware/rateLimit.ts';
import {
  addMessage, audit, createProject, deleteProject, getOrCreateConversation, getProjectForOwner,
  listMessages, listProjects, slugify, touchProject, type ProjectKind,
} from '../services/projects.ts';
import { WorkspaceService } from '../services/workspace.ts';
import { TEMPLATES, applyTemplate, ensureGradleWrapper, findTemplate } from '../services/templates.ts';
import { runTerminalCommand, listCommands } from '../services/terminal.ts';
import { runTests } from '../services/tests.ts';
import { getBuild, latestApk, listBuilds, runBuild } from '../services/build.ts';
import { exportZip } from '../services/export.ts';
import { scanProject } from '../services/securityScan.ts';
import {
  cancelGithubBuild, getGithubBuild, githubApkPath, listGithubBuilds, startGithubBuild,
} from '../services/githubBuilds.ts';
import { fetchRunLogs, credentialKind } from '../services/githubActions.ts';
import { syncWorkspaceToRepo, type SyncResult } from '../services/githubSync.ts';
import { previewApk } from '../services/androidPreview.ts';
import { inspectApk } from '../services/apkInspect.ts';
import { enqueueAgentRun } from '../agent/loop.ts';
import { aiRouter, isProviderId, isProviderSelection } from '../services/aiProvider.ts';
import { query } from '../db/pool.ts';
import { jobQueue } from '../services/jobQueue.ts';
import { PathSecurityError } from '../lib/paths.ts';
import { config } from '../config/index.ts';
import { logger } from '../lib/logger.ts';
import fs from 'node:fs/promises';
import path from 'node:path';

const router = Router();

router.use(requireAuth);

const terminalLimiter = rateLimit({ max: config.terminalRateLimitMax, keyPrefix: 'terminal' });
const agentLimiter = rateLimit({ max: config.agentRateLimitMax, keyPrefix: 'agent' });
const buildLimiter = rateLimit({ max: config.buildRateLimitMax, keyPrefix: 'build' });

function projectIdParam(req: Request): string {
  const id = req.params.id;
  if (!id) throw new HttpError(400, 'project id is required', 'invalid_project_id');
  return id;
}

async function loadOwnedProject(req: Request, required = true) {
  const id = projectIdParam(req);
  const owner = req.user!.id;
  const project = await getProjectForOwner(id, owner);
  if (!project) {
    // Distinguish malformed ids from genuine authorization failures in audit logs
    // while returning the same response, so ids cannot be probed.
    await audit({ userId: owner, action: 'project.access', outcome: 'denied', ip: req.ip ?? null, detail: { id } });
    if (required) throw new HttpError(404, 'project not found', 'project_not_found');
  }
  return project;
}

const createProjectSchema = z.object({
  name: z.string().min(1).max(120),
  description: z.string().max(2000).optional(),
  template: z.string().max(64).default('blank'),
  kind: z.enum(['generic', 'android', 'node', 'static']).optional(),
});

router.get('/templates', asyncHandler(async (_req, res) => {
  res.json({ templates: TEMPLATES });
}));

router.get('/', asyncHandler(async (req, res) => {
  const limit = Math.min(Number(req.query.limit ?? 50) || 50, 100);
  const offset = Math.max(Number(req.query.offset ?? 0) || 0, 0);
  const projects = await listProjects(req.user!.id, limit, offset);
  res.json({ projects, limit, offset });
}));

router.post('/', asyncHandler(async (req, res) => {
  const body = validate(createProjectSchema, req.body);
  const template = findTemplate(body.template);
  if (body.template !== 'blank' && !template) {
    throw new HttpError(400, `unknown template: ${body.template}`, 'unknown_template');
  }
  const kind: ProjectKind = body.kind ?? template?.kind ?? 'generic';

  // Slug uniqueness is per owner, so retry with a suffix on collision.
  let slug = slugify(body.name);
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const candidate = attempt === 0 ? slug : `${slug}-${Math.random().toString(36).slice(2, 6)}`;
    try {
      const project = await createProject({
        ownerId: req.user!.id,
        name: body.name,
        slug: candidate,
        description: body.description,
        template: template?.id ?? 'blank',
        kind,
        packageName: template?.packageName ?? null,
      });
      slug = candidate;

      const ws = new WorkspaceService(project.id);
      await ws.ensure();
      await applyTemplate(project.id, template?.id ?? 'blank', project.name);

      // Android projects need a real Gradle wrapper to be buildable. The files
      // are installed from vendored assets rather than generated by `gradle
      // wrapper`, which can hang for minutes on a cold environment.
      if (kind === 'android') {
        const wrapper = await ensureGradleWrapper(project.id);
        logger.info('gradle wrapper install', {
          projectId: project.id, ok: wrapper.ok, detail: wrapper.detail,
        });
      }

      await audit({ userId: req.user!.id, projectId: project.id, action: 'project.create', ip: req.ip ?? null, detail: { template: project.template } });
      res.status(201).json({ project });
      return;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      if (/projects_owner_slug_key|duplicate key/i.test(message) && attempt < 4) continue;
      throw err;
    }
  }
  throw new HttpError(500, 'could not allocate a unique project slug', 'slug_allocation_failed');
}));

router.get('/:id', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const ws = new WorkspaceService(project!.id);
  const [fileCount, totalSize] = await Promise.all([
    ws.list('.', 20).then((f) => f.length),
    ws.totalSize().catch(() => 0),
  ]);
  res.json({ project, workspace: { fileCount, totalSize, path: ws.root } });
}));

router.delete('/:id', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const ws = new WorkspaceService(project!.id);
  // Remove the workspace from disk first so a deleted project leaves nothing behind.
  await fs.rm(ws.root, { recursive: true, force: true }).catch(() => undefined);
  const removed = await deleteProject(project!.id, req.user!.id);
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'project.delete', outcome: removed ? 'ok' : 'not_found', ip: req.ip ?? null });
  res.json({ ok: removed });
}));

// ------------------------------- files ---------------------------------------

const writeFileSchema = z.object({
  path: z.string().min(1).max(500),
  content: z.string().max(config.maxFileBytes),
});

router.get('/:id/files', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const ws = new WorkspaceService(project!.id);
  const dir = typeof req.query.dir === 'string' ? req.query.dir : '.';
  const depth = Math.min(Number(req.query.depth ?? 4) || 4, 8);
  const files = await ws.list(dir, depth);
  res.json({ files, root: ws.root });
}));

router.get('/:id/file', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const relPath = req.query.path;
  if (typeof relPath !== 'string' || relPath.length === 0) {
    throw new HttpError(400, 'query parameter "path" is required', 'missing_path');
  }
  const ws = new WorkspaceService(project!.id);
  try {
    const file = await ws.read(relPath);
    res.json(file);
  } catch (err) {
    if (err instanceof PathSecurityError) {
      await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.read', outcome: 'path_traversal_blocked', ip: req.ip ?? null, detail: { path: relPath } });
      throw new HttpError(400, 'invalid file path', 'invalid_path');
    }
    throw new HttpError(404, err instanceof Error ? err.message : 'file not found', 'file_not_found');
  }
}));

router.post('/:id/file', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(writeFileSchema, req.body);
  const ws = new WorkspaceService(project!.id);
  await ws.ensure();
  try {
    const result = await ws.create(body.path, body.content);
    await touchProject(project!.id);
    await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.create', ip: req.ip ?? null, detail: { path: body.path, created: result.created } });
    res.status(result.created ? 201 : 200).json(result);
  } catch (err) {
    if (err instanceof PathSecurityError) {
      await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.create', outcome: 'path_traversal_blocked', ip: req.ip ?? null, detail: { path: body.path } });
      throw new HttpError(400, 'invalid file path', 'invalid_path');
    }
    throw err;
  }
}));

router.put('/:id/file', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(writeFileSchema, req.body);
  const ws = new WorkspaceService(project!.id);
  await ws.ensure();
  try {
    const result = await ws.write(body.path, body.content);
    await touchProject(project!.id);
    await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.write', ip: req.ip ?? null, detail: { path: body.path, size: result.size } });
    res.json(result);
  } catch (err) {
    if (err instanceof PathSecurityError) {
      await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.write', outcome: 'path_traversal_blocked', ip: req.ip ?? null, detail: { path: body.path } });
      throw new HttpError(400, 'invalid file path', 'invalid_path');
    }
    throw err;
  }
}));

router.delete('/:id/file', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const relPath = req.query.path;
  if (typeof relPath !== 'string' || relPath.length === 0) {
    throw new HttpError(400, 'query parameter "path" is required', 'missing_path');
  }
  const ws = new WorkspaceService(project!.id);
  try {
    const result = await ws.remove(relPath);
    await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.delete', ip: req.ip ?? null, detail: { path: relPath } });
    res.json(result);
  } catch (err) {
    if (err instanceof PathSecurityError) {
      await audit({ userId: req.user!.id, projectId: project!.id, action: 'file.delete', outcome: 'path_traversal_blocked', ip: req.ip ?? null, detail: { path: relPath } });
      throw new HttpError(400, 'invalid file path', 'invalid_path');
    }
    throw err;
  }
}));

router.get('/:id/search', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const q = req.query.q;
  if (typeof q !== 'string' || q.length === 0) throw new HttpError(400, 'query parameter "q" is required', 'missing_query');
  const ws = new WorkspaceService(project!.id);
  const matches = await ws.search(q, {
    regex: req.query.regex === 'true',
    maxResults: Math.min(Number(req.query.maxResults ?? 100) || 100, 500),
  });
  res.json({ matches, count: matches.length });
}));

// ----------------------------- conversations ---------------------------------

router.get('/:id/conversation', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const conversation = await getOrCreateConversation(project!.id, req.user!.id);
  const limit = Math.min(Number(req.query.limit ?? 50) || 50, 200);
  const before = typeof req.query.before === 'string' ? req.query.before : undefined;
  const messages = await listMessages(conversation.id, limit, before);
  res.json({ conversation, messages });
}));

// ------------------------------- terminal ------------------------------------

const terminalSchema = z.object({ command: z.string().min(1).max(4000) });

router.post('/:id/terminal', terminalLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(terminalSchema, req.body);
  const result = await runTerminalCommand({
    projectId: project!.id,
    ownerId: req.user!.id,
    command: body.command,
    source: 'terminal',
  });
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'terminal.run', outcome: result.status, ip: req.ip ?? null, detail: { command: body.command.slice(0, 200), exitCode: result.exitCode } });
  res.json(result);
}));

router.get('/:id/terminal', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const commands = await listCommands(project!.id, 25);
  res.json({ commands });
}));

// --------------------------------- agent -------------------------------------

const agentSchema = z.object({
  prompt: z.string().min(1).max(8000),
  // 'auto' lets the router pick and fail over; a provider id pins the run. The
  // set is validated against the router's own registry rather than a hand-written
  // list, which had drifted and rejected providers the router actually supports.
  provider: z.string().max(40).optional(),
});

router.post('/:id/agent/run', agentLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(agentSchema, req.body);
  // The router is the authority on which providers exist; an unknown id is a
  // client error rather than a run that silently falls back to AUTO.
  if (body.provider !== undefined && body.provider !== 'auto' && !isProviderId(body.provider)) {
    throw new HttpError(400, `unknown provider: ${body.provider}`, 'unknown_provider');
  }
  const provider = body.provider ?? (isProviderSelection(config.aiDefaultProvider) ? config.aiDefaultProvider : 'auto');
  const conversation = await getOrCreateConversation(project!.id, req.user!.id);
  await addMessage(conversation.id, 'user', body.prompt);

  const providerModel = provider === 'auto'
    ? aiRouter.autoOrder().ready[0] ? aiRouter.adapter(aiRouter.autoOrder().ready[0]).status().model : null
    : aiRouter.adapter(provider).status().model;

  const runRow = await query<{ id: string }>(
    `INSERT INTO agent_runs (project_id, conversation_id, owner_id, prompt, status, phase, model, max_fix_attempts)
     VALUES ($1, $2, $3, $4, 'queued', 'queued', $5, $6) RETURNING id`,
    [project!.id, conversation.id, req.user!.id, body.prompt, providerModel, config.maxFixAttempts],
  );
  const agentRunId = runRow.rows[0].id;

  await audit({ userId: req.user!.id, projectId: project!.id, action: 'agent.run.start', ip: req.ip ?? null, detail: { agentRunId, provider } });

  // Run asynchronously; progress reaches the client over WebSocket.
  void enqueueAgentRun({
    projectId: project!.id,
    ownerId: req.user!.id,
    prompt: body.prompt,
    agentRunId,
    conversationId: conversation.id,
    provider,
  }).then(async (outcome) => {
    await addMessage(conversation.id, 'assistant', outcome.summary, { agentRunId, status: outcome.status });
    await audit({ userId: req.user!.id, projectId: project!.id, action: 'agent.run.finish', outcome: outcome.status, detail: { agentRunId } });
  }).catch(async (err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    await query(`UPDATE agent_runs SET status = 'failed', phase = 'failed', error = $2, finished_at = now() WHERE id = $1`, [agentRunId, message]).catch(() => undefined);
    logger.error('agent run crashed', { agentRunId, error: message });
  });

  res.status(202).json({ agentRunId, status: 'queued', wsUrl: `/ws?projectId=${project!.id}` });
}));

router.get('/:id/agent/runs', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const runs = await query(
    `SELECT id, status, phase, model, provider, failover_from, failover_reason,
            fix_attempts, max_fix_attempts, summary, error, tokens_in, tokens_out,
            created_at, started_at, finished_at
     FROM agent_runs WHERE project_id = $1 ORDER BY created_at DESC LIMIT 20`,
    [project!.id],
  );
  res.json({ runs: runs.rows });
}));

router.post('/:id/agent/runs/:runId/cancel', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const runId = req.params.runId;
  const cancelled = jobQueue.cancel(`agent:${runId}`);
  if (cancelled) {
    await query(`UPDATE agent_runs SET status = 'cancelled', phase = 'failed', error = 'cancelled by user', finished_at = now() WHERE id = $1 AND project_id = $2`, [runId, project!.id]);
  }
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'agent.run.cancel', outcome: cancelled ? 'ok' : 'not_running', detail: { runId } });
  res.json({ cancelled });
}));

// ------------------------------- tests ---------------------------------------

router.post('/:id/test', buildLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const result = await runTests({ projectId: project!.id, ownerId: req.user!.id });
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'test.run', outcome: result.status, ip: req.ip ?? null, detail: { framework: result.framework } });
  res.json({ test: result });
}));

router.get('/:id/tests', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const rows = await query(
    `SELECT id, framework, command, status, passed, failed, skipped, duration_ms, error, created_at, finished_at
     FROM tests WHERE project_id = $1 ORDER BY created_at DESC LIMIT 20`,
    [project!.id],
  );
  res.json({ tests: rows.rows });
}));

// ------------------------------- builds --------------------------------------

const buildSchema = z.object({ target: z.enum(['debug', 'release']).default('debug') });

router.post('/:id/build', buildLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(buildSchema, req.body ?? {});
  const result = await runBuild({ projectId: project!.id, ownerId: req.user!.id, target: body.target });
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'build.run', outcome: result.status, ip: req.ip ?? null, detail: { target: body.target, buildId: result.id } });
  res.json({
    build: {
      id: result.id, kind: result.kind, target: result.target, status: result.status,
      command: result.command, exitCode: result.exitCode, durationMs: result.durationMs,
      apk: result.apk, inspection: result.inspection, security: result.security, error: result.error,
      logTail: result.log.slice(-40000),
    },
  });
}));

router.get('/:id/builds', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  res.json({ builds: await listBuilds(project!.id) });
}));

router.get('/:id/build/:buildId', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const build = await getBuild(project!.id, req.params.buildId!);
  if (!build) throw new HttpError(404, 'build not found', 'build_not_found');
  res.json({ build });
}));

router.post('/:id/build/:buildId/inspect-apk', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const build = await getBuild(project!.id, req.params.buildId!) as { apk_path: string | null } | null;
  if (!build) throw new HttpError(404, 'build not found', 'build_not_found');
  if (!build.apk_path) throw new HttpError(409, 'this build has no APK', 'no_apk');
  const inspection = await inspectApk(build.apk_path);
  res.json({ inspection });
}));

// ----------------------------- security scan ---------------------------------

router.post('/:id/security/scan', buildLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const apk = await latestApk(project!.id);
  const scan = await scanProject(project!.id, apk?.path ?? null);
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'security.scan', outcome: scan.status, ip: req.ip ?? null });
  res.json({ scan });
}));

router.get('/:id/security/scans', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const rows = await query(
    `SELECT id, status, findings, files_scanned, created_at FROM security_scans WHERE project_id = $1 ORDER BY created_at DESC LIMIT 10`,
    [project!.id],
  );
  res.json({ scans: rows.rows });
}));

// ------------------------------- preview -------------------------------------

router.post('/:id/preview', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const apk = await latestApk(project!.id);
  let packageName: string | null = null;
  if (apk) {
    const inspection = await inspectApk(apk.path);
    packageName = inspection.packageName;
  }
  const result = await previewApk({ apkPath: apk?.path ?? null, packageName });
  res.json({ preview: result });
}));

// -------------------------------- export -------------------------------------

router.post('/:id/export', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const result = await exportZip({ projectId: project!.id, ownerId: req.user!.id });
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'export.zip', outcome: result.ok ? 'ok' : 'failed', ip: req.ip ?? null, detail: { sizeBytes: result.sizeBytes, leaks: result.excludedEntries.length } });
  res.json({ export: result });
}));

router.get('/:id/artifacts', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const rows = await query(
    `SELECT id, kind, rel_path, size_bytes, sha256, created_at FROM artifacts WHERE project_id = $1 ORDER BY created_at DESC LIMIT 30`,
    [project!.id],
  );
  res.json({ artifacts: rows.rows });
}));

router.get('/:id/download/apk', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const apk = await latestApk(project!.id);
  if (!apk) throw new HttpError(404, 'no APK has been generated for this project', 'no_apk');
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'download.apk', ip: req.ip ?? null });
  res.setHeader('Content-Type', 'application/vnd.android.package-archive');
  res.download(apk.path, path.basename(apk.path));
}));

router.get('/:id/download/zip', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const result = await exportZip({ projectId: project!.id, ownerId: req.user!.id });
  if (!result.ok || !result.zipPath) {
    throw new HttpError(500, result.error ?? 'export failed', 'export_failed');
  }
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'download.zip', ip: req.ip ?? null });
  res.download(result.zipPath, `project-${project!.slug}.zip`);
}));

router.get('/:id/download/logs', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const builds = await query<{ log: string; command: string | null; created_at: Date; status: string }>(
    `SELECT log, command, created_at, status FROM builds WHERE project_id = $1 ORDER BY created_at DESC LIMIT 5`,
    [project!.id],
  );
  const header = [
    `My AI Studio build logs`,
    `project: ${project!.name} (${project!.id})`,
    `generated: ${new Date().toISOString()}`,
    '',
  ].join('\n');
  const body = builds.rows
    .map((b) => `===== ${b.created_at.toISOString()} [${b.status}] ${b.command ?? ''} =====\n${b.log}`)
    .join('\n\n');
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'download.logs', ip: req.ip ?? null });
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${project!.slug}-build-logs.txt"`);
  res.send(header + body);
}));

// ----------------------------- GitHub Actions --------------------------------
//
// A build is dispatched on GitHub and then tracked. The project is always loaded
// through loadOwnedProject first, so a build can only ever be started, read,
// cancelled or downloaded by the owner of the project. The GitHub credential
// stays on the server: the browser only ever receives project-scoped ids.

const githubBuildLimiter = rateLimit({ max: config.githubBuildRateLimitMax, keyPrefix: 'github_build' });

const githubBuildSchema = z.object({
  // Constrained so a request cannot name an arbitrary workflow, repository or
  // ref pattern; the server still re-checks the workflow against its
  // configuration before dispatching.
  repository: z.string().regex(/^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/).max(140).optional(),
  branch: z.string().regex(/^[A-Za-z0-9._/-]{1,120}$/).optional(),
  workflow: z.string().max(120).optional(),
  // Publishes the workspace to the repository before dispatching. On by default
  // because a runner checks out the repository, not this server, so a build of
  // unsynced code would not build what the user sees.
  sync: z.boolean().optional(),
});

router.post('/:id/github/build', githubBuildLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(githubBuildSchema, req.body ?? {});

  // Publish first so the run builds the current workspace rather than whatever
  // was in the repository before. Skipped when there is no repository or no
  // credential, so the tracking row can report not_configured precisely instead
  // of failing on a publish that could never have worked.
  const effectiveRepo = body.repository || config.githubRepo;
  let sync: SyncResult | null = null;
  if (body.sync !== false && effectiveRepo && credentialKind() !== 'none') {
    sync = await syncWorkspaceToRepo({
      projectId: project!.id,
      repo: body.repository,
      branch: body.branch,
      message: `My AI Studio: build ${project!.slug} (${new Date().toISOString()})`,
    });
    await audit({
      userId: req.user!.id, projectId: project!.id, action: 'github.sync',
      outcome: sync.ok ? 'ok' : 'failed', ip: req.ip ?? null,
      detail: { repo: sync.repo, branch: sync.branch, files: sync.filesPushed },
    });
    if (!sync.ok) {
      // A failed publish is a real blocker: say so instead of dispatching a run
      // that would build stale code.
      logger.warn('github sync failed before build', { projectId: project!.id, error: sync.error ?? null });
      res.status(502).json({
        error: 'the project could not be published to GitHub, so no workflow was dispatched',
        detail: sync.error ?? null,
        skipped: sync.skipped.slice(0, 50),
      });
      return;
    }
  }

  const build = await startGithubBuild({
    projectId: project!.id,
    ownerId: req.user!.id,
    repo: body.repository ?? sync?.repo,
    branch: body.branch ?? sync?.branch,
    workflow: body.workflow,
  });
  await audit({
    userId: req.user!.id, projectId: project!.id, action: 'github.build',
    outcome: build.status, ip: req.ip ?? null,
    detail: { repo: build.repo, runId: build.runId, workflow: build.workflow },
  });
  // 202: the run is tracked, not finished. The status field says what actually
  // happened, including not_configured and blocked.
  res.status(202).json({ build, sync: sync ? { ...sync, skipped: sync.skipped.slice(0, 50) } : null });
}));

/** Publishes the workspace to GitHub without dispatching a workflow. */
router.post('/:id/github/sync', githubBuildLimiter, asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const body = validate(githubBuildSchema, req.body ?? {});
  const sync = await syncWorkspaceToRepo({
    projectId: project!.id, repo: body.repository, branch: body.branch,
    message: `My AI Studio: sync ${project!.slug}`,
  });
  await audit({
    userId: req.user!.id, projectId: project!.id, action: 'github.sync',
    outcome: sync.ok ? 'ok' : 'failed', ip: req.ip ?? null,
    detail: { repo: sync.repo, branch: sync.branch, files: sync.filesPushed },
  });
  if (!sync.ok) {
    res.status(502).json({ error: sync.error ?? 'sync failed', sync: { ...sync, skipped: sync.skipped.slice(0, 50) } });
    return;
  }
  res.json({ sync: { ...sync, skipped: sync.skipped.slice(0, 50) } });
}));

router.get('/:id/github/builds', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  res.json({ builds: await listGithubBuilds(project!.id) });
}));

router.get('/:id/github/build/:buildId', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const build = await getGithubBuild(req.params.buildId!, project!.id);
  if (!build) throw new HttpError(404, 'github build not found', 'github_build_not_found');
  res.json({ build });
}));

router.post('/:id/github/build/:buildId/cancel', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const result = await cancelGithubBuild(req.params.buildId!, project!.id);
  if (!result.ok) throw new HttpError(409, result.error ?? 'cancel failed', 'github_cancel_failed');
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'github.cancel', outcome: 'ok', ip: req.ip ?? null, detail: { buildId: req.params.buildId } });
  const build = await getGithubBuild(req.params.buildId!, project!.id);
  res.json({ build });
}));

router.get('/:id/github/build/:buildId/logs', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const build = await getGithubBuild(req.params.buildId!, project!.id);
  if (!build) throw new HttpError(404, 'github build not found', 'github_build_not_found');
  if (!build.runId) {
    // No run has been assigned yet, so there is no remote log to fetch. The
    // local tail is everything that exists at this point.
    res.json({ logs: build.logTail, remote: null });
    return;
  }
  const remote = await fetchRunLogs(build.repo, build.runId);
  res.json({ logs: build.logTail, remote: remote.ok ? remote.text : null, error: remote.ok ? null : remote.error ?? null });
}));

/**
 * Serves the APK that GitHub Actions actually produced. The bytes come from the
 * artifact download, were validated as a real APK, and were written to storage
 * under this project. Nothing is renamed or synthesised: a build without a
 * verified APK answers 404.
 */
router.get('/:id/github/build/:buildId/apk', asyncHandler(async (req, res) => {
  const project = await loadOwnedProject(req);
  const buildId = req.params.buildId!;
  const build = await getGithubBuild(buildId, project!.id);
  if (!build) throw new HttpError(404, 'github build not found', 'github_build_not_found');
  if (build.status !== 'success' || !build.apk?.valid) {
    throw new HttpError(404, `no verified APK for this build (status ${build.status})`, 'github_apk_unavailable');
  }
  const apkPath = await githubApkPath(buildId, project!.id);
  if (!apkPath) throw new HttpError(404, 'the APK for this build is no longer on disk', 'github_apk_missing');
  await audit({ userId: req.user!.id, projectId: project!.id, action: 'github.download.apk', ip: req.ip ?? null, detail: { buildId, runId: build.runId } });
  res.setHeader('Content-Type', 'application/vnd.android.package-archive');
  res.download(apkPath, build.apk.name);
}));

export default router;
